setvol: add volume protection check
After almost blewing my eardrums with a shell cmd typo...

Signed-off-by: Ioan-Adrian Ratiu <adi@adirat.com>

diff --git a/layers/meta-10n1x/recipes-multimedia/shplay/shplay/setvol b/layers/meta-10n1x/recipes-multimedia/shplay/shplay/setvol
--- a/layers/meta-10n1x/recipes-multimedia/shplay/shplay/setvol
+++ b/layers/meta-10n1x/recipes-multimedia/shplay/shplay/setvol
@@ -1,2 +1,14 @@
 #!/bin/bash
+
+if (( $# != 1 )); then
+    echo "Illegal number of parameters"
+    echo "Usage: $0 <volume-number>"
+    exit 1
+fi
+
+if [ "$1" -ge 120 ]; then
+    echo "ERROR: Volume value $1 is too high"
+    exit 1
+fi
+
 amixer sset Digital "$@"
